# Generated by Django 4.2.2 on 2023-06-17 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisements", "0003_remove_advertisement_is_favorite_favorite"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="test",
            field=models.TextField(default=""),
        ),
    ]
