# Generated by Django 4.2.1 on 2023-05-07 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_studentteacher"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentTeacher",
        ),
    ]
