# Generated by Django 4.2.1 on 2023-06-03 16:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0002_alter_measurement_options_alter_sensor_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="date_time",
            new_name="created_at",
        ),
    ]
