# Generated by Django 4.2.1 on 2023-06-03 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0003_rename_date_time_measurement_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="id_sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="measurement.sensor",
            ),
        ),
    ]
