# Generated by Django 4.2.1 on 2023-06-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0004_alter_measurement_id_sensor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={},
        ),
        migrations.AlterModelOptions(
            name="sensor",
            options={},
        ),
        migrations.RenameField(
            model_name="measurement",
            old_name="id_sensor",
            new_name="sensor",
        ),
        migrations.AddField(
            model_name="measurement",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="temperature",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="description",
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
