# Generated by Django 4.2.1 on 2023-06-03 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measurement",
            options={"verbose_name": "Измерение", "verbose_name_plural": "Измерения"},
        ),
        migrations.AlterModelOptions(
            name="sensor",
            options={"verbose_name": "Датчик", "verbose_name_plural": "Датчики"},
        ),
    ]
