# Generated by Django 4.2.1 on 2023-06-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0006_alter_measurement_options_alter_sensor_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="sensor",
            new_name="id_sensor",
        ),
        migrations.AlterField(
            model_name="measurement",
            name="temperature",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="description",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
    ]
