# Generated by Django 4.2.1 on 2023-06-04 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("measurement", "0007_rename_sensor_measurement_id_sensor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="id_sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="measurement.sensor",
                verbose_name="Датчик",
            ),
        ),
        migrations.AlterField(
            model_name="measurement",
            name="temperature",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Температура"
            ),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="description",
            field=models.CharField(max_length=100, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="sensor",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Название датчика"),
        ),
    ]
